begin project
Deseteral/lebkuchen-fm-macos pull request #1
Opened 2021-10-05 21:30 UTC by gorzalczany

![Zrzut ekranu 2021-10-5 o 23 29 49](https://user-images.githubusercontent.com/4126066/136105368-c57ce4d6-e737-4670-a2a1-7d5aaf1b2c7a.png)

2021-10-06 15:13 UTC, Deseteral approved these changes

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-mac/App.swift
> +struct x_sounds_macApp: App {
Mixed case is not cool

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-mac/AppStorageKeys.swift
> +    case slackChanelId
```suggestion
    case slackChannelId
```

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-mac/AppStorageKeys.swift
> +    case FMinstancePath
Mixed case again. Shouldn't this be
```suggestion
    case fmInstancePath
```
instead?

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-mac/Domain/XSound/XSoundPlayer.swift
> +    func playSound(sound: URL, id: String){
```suggestion
    func playSound(sound: URL, id: String) {
```

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-mac/Domain/XSound/XSoundsEndpointService.swift
> +        let urlString = instancePath + "x-sounds"
My preference would be to do string interpolation instead of addition (my that's just my code style opinion)
```suggestion
        let urlString = "\(instancePath)x-sounds"
```

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-mac/Domain/XSound/XSoundsEndpointService.swift
> +        var request = URLRequest(url: URL(string: urlString)!)
Probably a good idea to do `guard let` on URL init in case someone enters service URL wrong (without `/` at the end for example).

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-mac/Domain/XSound/XSoundsEndpointService.swift
> +        let urlString = instancePath + "x-sounds"
Why are you not using `appendingPathComponent` fot this?

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-mac/Services/PasteToSlack.swift
> +    func paste(text:String) {
```suggestion
    func paste(text: String) {
```

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-mac/Services/PasteToSlack.swift
> +        let url = URL(string: "slack://channel?team=\(slackTeamId)&id=\(slackChanelId)")!
Same thing here - isn't it better to use URLs `QueryItems`?

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-mac/Views/SoundsList/SoundsList.swift
> +                    Text("Download x-sounds")
```suggestion
                    Text("Fetch XSounds list")
```

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-mac/Views/SoundsList/SoundsList.swift
> +                        viewModel.sounds.filter {
Introducing computed property instead of this would be cleaner

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-mac/Views/SoundsList/SoundsList.swift
> +                            if soundManager.failed.contains(sound.id) {
This should not occur anymore

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-mac/Views/SoundsList/SoundsList.swift
> +                Button(action: {
Instead of having this on button, we could do it in `onAppear` instead.
Or have initial fetch in `onAppear` and refresh button here.

2021-10-06 15:13 UTC, Deseteral commented on x-sounds-macTests/x_sounds_macTests.swift
> +}
Solid tests are always good to see 👍

2021-10-06 15:25 UTC, gorzalczany commented on x-sounds-mac/Services/PasteToSlack.swift
> +        let url = URL(string: "slack://channel?team=\(slackTeamId)&id=\(slackChanelId)")!
It is

2021-10-10 21:40 UTC, gorzalczany commented on x-sounds-mac/Views/SoundsList/SoundsList.swift
> +                            if soundManager.failed.contains(sound.id) {
It may fail due to problems other than 404. Let's leave it as is.

2021-10-11 18:26 UTC, Deseteral commented on x-sounds-mac/Views/SoundsList/SoundsList.swift
> +                            if soundManager.failed.contains(sound.id) {
Fine.

2021-10-11 18:32 UTC, Deseteral requested changes
Almost there Słodziaku, almost there :D

2021-10-11 18:32 UTC, Deseteral commented on x-sounds-mac/Domain/XSound/XSoundsEndpointService.swift
> +        var request = URLRequest(url: url.appendingPathComponent("x-sounds", isDirectory: true))
Shouldn't `isDirectory` be false?
```suggestion
        var request = URLRequest(url: url.appendingPathComponent("x-sounds", isDirectory: false))
```

It should do `GET /x-sounds`, not `GET /x-sounds/`

2021-10-11 20:01 UTC, Deseteral approved these changes

2021-10-11 20:04 UTC, merged